var searchData=
[
  ['l_20interface_20graphique_0',['&lt;b&gt;L&apos;interface graphique&lt;/b&gt;',['../index.html#autotoc_md24',1,'']]],
  ['l_20objectif_1',['L&apos;objectif',['../index.html#autotoc_md1',1,'']]],
  ['l_20objectif_20yanis_20diapo_201_20logo_2',['L&apos;objectif [Yanis] - Diapo 1 (logo)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['la_20balle_3',['&lt;b&gt;Choisir le type de la balle&lt;/b&gt;',['../index.html#autotoc_md17',1,'']]],
  ['la_20balle_20dounia_4',['&lt;b&gt;Choisir le type de la balle [Dounia]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md59',1,'']]],
  ['la_20demo_5',['PENDANT LA DEMO',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md81',1,'']]],
  ['la_20demo_20_3a_20vasilis_6',['Compilation [pendant la demo : Vasilis]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md82',1,'']]],
  ['la_20logique_20du_20jeu_7',['&lt;b&gt;La logique du jeu&lt;/b&gt;',['../index.html#autotoc_md23',1,'']]],
  ['la_20musique_8',['&lt;b&gt;Changement de la musique&lt;/b&gt;',['../index.html#autotoc_md18',1,'']]],
  ['la_20musique_20yanis_9',['&lt;b&gt;Changement de la musique [Yanis]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['lambda_10',['Fonctions lambda',['../index.html#autotoc_md29',1,'']]],
  ['lambda_20explication_20c_20est_20quoi_20en_20relaite_20def_20suffit_20pas_20dounia_11',['Fonctions lambda + Explication c&apos;est quoi en relaite (def suffit pas) [Dounia]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md69',1,'']]],
  ['lancement_12',['lancement',['../index.html#autotoc_md5',1,'Instructions de lancement'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md84',1,'Instructions de lancement']]],
  ['last_5fhighscore_13',['last_highscore',['../class_game.html#a39428b5c8de846dbdd5efb1be52c9066',1,'Game']]],
  ['last_5fhighscore_5fname_14',['last_highscore_name',['../class_game.html#aeedf815028a7cfc54159f05ee2de7ec4',1,'Game']]],
  ['le_20jeu_15',['Le jeu',['../index.html#autotoc_md2',1,'']]],
  ['le_20jeu_20yanis_20diapo_202_20un_20jue_20lequel_16',['Le jeu [Yanis] - Diapo 2 (Un jue, lequel)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'']]],
  ['le_20type_20de_20la_20balle_17',['&lt;b&gt;Choisir le type de la balle&lt;/b&gt;',['../index.html#autotoc_md17',1,'']]],
  ['le_20type_20de_20la_20balle_20dounia_18',['&lt;b&gt;Choisir le type de la balle [Dounia]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md59',1,'']]],
  ['lequel_19',['Le jeu [Yanis] - Diapo 2 (Un jue, lequel)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'']]],
  ['les_20concepts_20clés_20diapo_206_20',['&lt;b&gt;Les concepts clés - Diapo 6&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['les_20différents_20modes_21',['Les différents modes',['../index.html#autotoc_md8',1,'']]],
  ['les_20différents_20modes_20diapo_203_20ou_22',['Les différents modes - Diapo 3 ou +++',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['les_20foncteurs_23',['&lt;b&gt;Les foncteurs&lt;/b&gt;',['../index.html#autotoc_md21',1,'']]],
  ['les_20foncteurs_20vasilis_24',['&lt;b&gt;Les foncteurs [Vasilis]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md72',1,'']]],
  ['les_20objets_25',['&lt;b&gt;Les objets&lt;/b&gt;',['../index.html#autotoc_md20',1,'']]],
  ['les_20objets_201_20yanis_202_20dounia_203_20vasilis_20diapo_205_26',['&lt;b&gt;Les objets [1. Yanis, 2. Dounia, 3. Vasilis ] - Diapo 5&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md63',1,'']]],
  ['les_20petits_20plus_20diapo_204_27',['Fonctionalites (Les petits plus) - Diapo 4',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['les_20tests_28',['Les tests',['../index.html#autotoc_md33',1,'']]],
  ['letter_29',['Letter',['../class_letter.html',1,'Letter'],['../class_letter.html#ad7d6b89bf521e852dc85cb658a32f653',1,'Letter::Letter(int index, float startX, float startY, float velocity, SDL_Renderer *renderer, TTF_Font *font)']]],
  ['letter_30',['letter',['../class_letter.html#add29e231aa209f890a891ea202dbff4a',1,'Letter']]],
  ['letter_2ecpp_31',['letter.cpp',['../letter_8cpp.html',1,'']]],
  ['letter_2ehpp_32',['letter.hpp',['../letter_8hpp.html',1,'']]],
  ['letter_5ftest_2ecpp_33',['letter_test.cpp',['../letter__test_8cpp.html',1,'']]],
  ['lettersatbottom_34',['lettersAtBottom',['../class_letter.html#a11286b566cff395d9f92b6184ca6bc1f',1,'Letter']]],
  ['load_5fgame_35',['load_game',['../class_saving.html#ab71b9324583e823beda155c1f84ff95d',1,'Saving']]],
  ['load_5fhighscore_36',['load_highscore',['../class_saving.html#aca0f68abac367530e21ec0140ed50cb8',1,'Saving']]],
  ['logic_37',['logic',['../index.html#autotoc_md16',1,'&lt;b&gt;Game retrieve logic&lt;/b&gt;'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md58',1,'&lt;b&gt;Game retrieve logic&lt;/b&gt;'],['../index.html#autotoc_md15',1,'&lt;b&gt;Game save logic&lt;/b&gt;'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md57',1,'&lt;b&gt;Game save logic&lt;/b&gt;']]],
  ['logique_20du_20jeu_38',['&lt;b&gt;La logique du jeu&lt;/b&gt;',['../index.html#autotoc_md23',1,'']]],
  ['logo_39',['L&apos;objectif [Yanis] - Diapo 1 (logo)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['loin_40',['Pour aller plus loin',['../index.html#autotoc_md38',1,'']]],
  ['loin_20vasilis_20diapo_208_41',['Pour aller plus loin [Vasilis] - Diapo 8',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md76',1,'']]],
  ['loop_42',['Loop',['../index.html#autotoc_md25',1,'']]],
  ['loop_43',['loop',['../class_game.html#a7ad92b77b596d7882a7ae76eb18b5e6c',1,'Game']]]
];
