var searchData=
[
  ['dépendances_0',['Dépendances',['../index.html#autotoc_md7',1,'Dépendances'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md85',1,'Dépendances']]],
  ['développement_1',['Autres aspects du développement',['../index.html#autotoc_md32',1,'']]],
  ['de_20la_20balle_2',['&lt;b&gt;Choisir le type de la balle&lt;/b&gt;',['../index.html#autotoc_md17',1,'']]],
  ['de_20la_20balle_20dounia_3',['&lt;b&gt;Choisir le type de la balle [Dounia]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md59',1,'']]],
  ['de_20la_20musique_4',['&lt;b&gt;Changement de la musique&lt;/b&gt;',['../index.html#autotoc_md18',1,'']]],
  ['de_20la_20musique_20yanis_5',['&lt;b&gt;Changement de la musique [Yanis]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md60',1,'']]],
  ['de_20lancement_6',['de lancement',['../index.html#autotoc_md5',1,'Instructions de lancement'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md84',1,'Instructions de lancement']]],
  ['def_20dounia_7',['Abstraction + Def [Dounia]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md68',1,'']]],
  ['def_20suffit_20pas_20dounia_8',['Fonctions lambda + Explication c&apos;est quoi en relaite (def suffit pas) [Dounia]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md69',1,'']]],
  ['def_20vasilis_9',['Encapsulation + Def [Vasilis]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md70',1,'']]],
  ['def_20yanis_10',['Def Yanis',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md66',1,'Héritage + Def [Yanis]'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md67',1,'Polymorphisme + Def [Yanis]']]],
  ['delete_5fhighscore_11',['delete_highscore',['../class_saving.html#a6faaf9d491dcf4ae1f60366b8415dad8',1,'Saving']]],
  ['delete_5fsave_12',['delete_save',['../class_saving.html#a165e2c1effaaf2c94eafb38341b1cad6',1,'Saving']]],
  ['demo_13',['PENDANT LA DEMO',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md81',1,'']]],
  ['demo_20_3a_20vasilis_14',['Compilation [pendant la demo : Vasilis]',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md82',1,'']]],
  ['des_20classes_20du_20jeu_15',['UML – Modélisation des classes du jeu',['../index.html#autotoc_md39',1,'']]],
  ['des_20données_16',['&lt;b&gt;Chiffrement des données&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['des_20données_20vasilis_17',['&lt;b&gt;Chiffrement des données [Vasilis]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md61',1,'']]],
  ['des_20pages_18',['&lt;b&gt;Structure des pages&lt;/b&gt;',['../index.html#autotoc_md22',1,'']]],
  ['des_20tests_19',['Organisation des tests',['../index.html#autotoc_md34',1,'']]],
  ['diapo_201_20logo_20',['L&apos;objectif [Yanis] - Diapo 1 (logo)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md44',1,'']]],
  ['diapo_202_20un_20jue_20lequel_21',['Le jeu [Yanis] - Diapo 2 (Un jue, lequel)',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md46',1,'']]],
  ['diapo_203_20ou_22',['Les différents modes - Diapo 3 ou +++',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['diapo_204_23',['Fonctionalites (Les petits plus) - Diapo 4',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md54',1,'']]],
  ['diapo_205_24',['&lt;b&gt;Les objets [1. Yanis, 2. Dounia, 3. Vasilis ] - Diapo 5&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md63',1,'']]],
  ['diapo_206_25',['&lt;b&gt;Les concepts clés - Diapo 6&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['diapo_207_26',['Problemes recnontres [Dounia] - Diapo 7',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md74',1,'']]],
  ['diapo_208_27',['Pour aller plus loin [Vasilis] - Diapo 8',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md76',1,'']]],
  ['diapo_209_28',['Conclusion [Yanis] - Diapo 9',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md78',1,'']]],
  ['différents_20modes_29',['Les différents modes',['../index.html#autotoc_md8',1,'']]],
  ['différents_20modes_20diapo_203_20ou_30',['Les différents modes - Diapo 3 ou +++',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['documentation_31',['Documentation',['../index.html#autotoc_md6',1,'']]],
  ['données_32',['&lt;b&gt;Chiffrement des données&lt;/b&gt;',['../index.html#autotoc_md19',1,'']]],
  ['données_20vasilis_33',['&lt;b&gt;Chiffrement des données [Vasilis]&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md61',1,'']]],
  ['dounia_34',['Dounia',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md59',1,'&lt;b&gt;Choisir le type de la balle [Dounia]&lt;/b&gt;'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md52',1,'&lt;b&gt;Fun mode [Dounia]&lt;/b&gt;'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md68',1,'Abstraction + Def [Dounia]'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md69',1,'Fonctions lambda + Explication c&apos;est quoi en relaite (def suffit pas) [Dounia]'],['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md51',1,'Storytime mode [Dounia]']]],
  ['dounia_203_20vasilis_20diapo_205_35',['&lt;b&gt;Les objets [1. Yanis, 2. Dounia, 3. Vasilis ] - Diapo 5&lt;/b&gt;',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md63',1,'']]],
  ['dounia_20diapo_207_36',['Problemes recnontres [Dounia] - Diapo 7',['../md__p_r_e_s_e_n_t_a_t_i_o_n.html#autotoc_md74',1,'']]],
  ['down_5fpressed_37',['down_pressed',['../struct_paddle_state.html#abe1a41ff6ae93404335fcf4f9d755c9d',1,'PaddleState']]],
  ['drawfilledcircle_38',['DrawFilledCircle',['../structcircle__renderer.html#ac40e4afb68f757ae34434ed4823a22f4',1,'circle_renderer::DrawFilledCircle()'],['../classic__ball_8cpp.html#a51e1c0f7fcd3e2b45855d8b851db3bc8',1,'DrawFilledCircle():&#160;classic_ball.cpp']]],
  ['du_20développement_39',['Autres aspects du développement',['../index.html#autotoc_md32',1,'']]],
  ['du_20jeu_40',['du jeu',['../index.html#autotoc_md23',1,'&lt;b&gt;La logique du jeu&lt;/b&gt;'],['../index.html#autotoc_md39',1,'UML – Modélisation des classes du jeu']]],
  ['duration_5feffect_41',['duration_effect',['../class_power.html#a29c7807215ab51efecde6056541a5b77',1,'Power']]]
];
